# Content configuration version
version: 2

# Personal info
name: Mónica Ledezma Ramírez
title: Técnica Administrativa y de Soporte TI 
email: 
phone: 86760558
# website: # If you have a personal website, add it here

# Social links - Add your usernames if you have these profiles
# twitter_username: 
  github_username: https://github.com/Monled02  
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
# linkedin_username: 
# xing_username: 
# pinterest_username: 
# youtube_username: 
# orcid_username: 
# googlescholar_username: 

# About Section
about_profile_image: images/profile.jpg # Replace with your image file path
about_content: |
  Técnica Administrativa y de Soporte TI proactiva y orientada al cliente. Combino habilidades sólidas en atención al cliente, soporte técnico y gestión administrativa para asegurar la eficiencia y la satisfacción en cada interacción. Me apasiona resolver problemas, optimizar procesos y contribuir al éxito de los equipos con los que trabajo.

content:
  - title: Proyectos Destacados 
    layout: list 
    content:
      - layout: left
        border: weak 
        title: Implementación de Gestión de Tickets 
        # link:  # If you have a link to a project showcase or portfolio, add it here
        link_text: Ver más 
        # additional_links:  # Uncomment and add links if available
        #   - title:  GitHub 
        #     icon: fab fa-github
        #     url:  
        quote: >
          Optimización del soporte técnico mediante la implementación de gestión de tickets
        description: | 
          * Analicé las necesidades del equipo y seleccioné un sistema adecuado
          * Configuré flujos de trabajo, categorías y prioridades
          * Capacité al equipo y brindé soporte durante la transición
          * Monitoreé el desempeño y realicé mejoras continuas

      - layout: left
        title: Optimización de Procesos Administrativos
        # link: 
        link_text: Ver más
        # additional_links:
        #   - title:  
        #     icon: fab fa-github
        #     url: 
        quote: > 
          Mejora de la eficiencia mediante la identificación y optimización de procesos clave
        description: |
          * Analicé flujos de trabajo e identifiqué áreas de mejora
          * Implementé soluciones para agilizar procesos (digitalización, estandarización)
          * Capacitación y seguimiento para asegurar la adopción de nuevos procesos
          * Reducción del tiempo de procesamiento y mejora en la organización

  - title: Experiencia Profesional
    layout: list
    content:
      - layout: right
        title: Backup IT Support
        sub_title: Técnica de Soporte de TI
        caption: Noviembre 2024 - Actualidad
        # link:  # Add company website if available
        quote: >
          
        description: | 
          * Brindé soporte técnico a usuarios, solucionando problemas de software y hardware, incluyendo instalación y configuración de aplicaciones, resolución de problemas de conectividad y asistencia en el uso de herramientas tecnológicas.
          * Realicé pruebas de equipos para asegurar su correcto funcionamiento, identificando y reportando cualquier problema técnico.
          * Configuré y solucioné problemas de redes inalámbricas y VPN, asegurando una conexión estable y segura para los usuarios.

      - layout: right
        title: Mudanzas Mundiales (Outsourcing de Amazon)
        sub_title: Técnica de Logística
        caption: Noviembre 2023 - Marzo 2024
        # link:  # Add company website if available
        quote: >
          
        description: |
          * Ejecuté tareas de logística a nivel nacional, incluyendo digitación de datos, seguimiento de envíos (trazabilidad) y asignación de equipos y suministros tecnológicos.
          * Gestioné documentación, asegurando que todos los registros estuvieran completos y actualizados.
          * Elaboré reportes estadísticos diarios y mantuve un archivo organizado de los movimientos de activos.
          * Brindé soporte a usuarios en problemas relacionados con software y hardware de TI

      - layout: right
        title: Exceltec (Outsourcing del BNCR)
        sub_title: Agente de Servicio al Cliente
        caption: Octubre 2022 - Abril 2023
        # link:  # Add company website if available
        quote: >
          
        description: | 
          * Atendí consultas y solicitudes de clientes a través de call center y canales en línea, brindando información clara y precisa sobre productos y servicios bancarios.
          * Manejé sistemas bancarios (ORACARD, SFB, ACCES) para procesar transacciones, como renovaciones de tarjetas, solicitudes de préstamos y consultas de saldo.
          * Realicé tareas operativas relacionadas con tarjetas de crédito y débito, incluyendo seguimiento de envíos, gestión de entregas especiales y manejo de cuentas de centralización.
          * Logré un alto nivel de satisfacción del cliente, resolviendo problemas de manera oportuna y eficiente

  - title: Formación Académica
    layout: list
    content:
      - layout: top-right
        title: Universidad Latina de Costa Rica
        sub_title: Asistente Administrativo Ejecutivo (Técnico)
        caption: 
        quote: >
          Adquirí conocimientos sólidos en gestión administrativa, incluyendo manejo de archivos, redacción de correspondencia, organización de reuniones y atención telefónica
        description: | 

      - layout: top-right
        title: Universidad Latina de Costa Rica 
        sub_title: Bachillerato en Trabajo Social
        caption: 
        quote: >
          Durante mis estudios, desarrollé habilidades clave en comunicación, empatía y resolución de conflictos
        description: | 
        
      - layout: top-right
        title: Ministerio de Educacion Publica MEP Costa Rica 
        sub_title: Bachillerato Educacion Media
        caption: "2013-2017"
        quote: >
          Bachillerato en Educacion Media

  - title: Más Sobre Mí
    layout: text
    content: | 
      * Apasionada por la tecnología y su aplicación para mejorar la eficiencia en el trabajo
      * Siempre busco aprender nuevas herramientas y metodologías para optimizar procesos
      * Disfruto trabajar en equipo y colaborar para alcanzar metas comunes
      * Me considero una persona proactiva, organizada y con gran capacidad de adaptación

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
